server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  session:
    store-type: redis
    redis:
      namespace: corespring:session
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
