server:
  servlet:
    session:
      timeout: 12h
      cookie:
        name: JSESSIONID

spring:
  session:
    store-type: redis
    redis:
      namespace: corespring:session
      time-to-live: 43200s
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
